### ISSUE TITLE
Expose various variables such as SHOW_SQL, DB_POOL_SIZE_MIN, DB_POOL_SIZE_MAX, DB_POOL_CONNECTIONS_COUNT

### ISSUE THREAD

**Issue by matiwinnetou** [cardano-foundation/cardano-rosetta-java#322]
Show SQL is now disabled, add a property so devs and DevOps can tweak and change it called: "SHOW_SQL" which can be either true or false.

In addition in the same ticket we should expose DB_POOL_SIZE_MIN, DB_POOL_SIZE_MAX and DB_POOL_CONNECTIONS_COUNT variables.

```
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
  mvc:
    log-resolved-exception: true
  output:
    ansi:
      enabled: always

```

```
spring:
  datasource:
    username: ${DB_USER:rosetta_db_admin}
    password: ${DB_SECRET:weakpwd#123_d}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:test}?currentSchema=${DB_SCHEMA:preprod}
    hikari:
      connectionTimeout: 100000 #default connection-timeout is 30 seconds
      minimumIdle: ${DB_POOL_SIZE_MIN:12} # default minimumIdle is 10
      connections: ${DB_POOL_CONNECTIONS_COUNT:48} # ((core_count * 2) + effective_spindle_count), 48 for 16 cores, NVMe Storage, spindle count 16

      keepaliveTime: 60000 # Sends a keep-alive query every 60s to prevent connection closure

      maximumPoolSize: ${DB_POOL_SIZE_MAX:24} # default pool size is 10
      leakDetectionThreshold: 60000
```
